/* automatically generated by rust-bindgen 0.72.0 */

#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum MessageCode {
    MSG_START = 33,
    FLOAT_AHEAD = 34,
    UINT_AHEAD = 35,
    INT_AHEAD = 36,
    SET = 37,
    GET = 38,
    ARM = 39,
    SHOULDER = 40,
    ELBOW = 41,
    CLAW = 42,
    DRIVE_TRAIN = 43,
    LIDAR = 44,
    MAGNETOMETER = 45,
    IR_BEACON = 46,
    TAPE_SENSOR = 47,
    ANGLE = 48,
    VELOCITY = 49,
    PID_ERROR = 50,
    PID_SETPOINT = 51,
    PID_ACCUMULATOR = 52,
    PID_KP = 53,
    PID_KI = 54,
    PID_KD = 55,
    PID_OUTPUT = 56,
    ALL = 57,
    NONE = 58,
    RAW = 59,
    CONVERTED = 60,
    LEFT = 61,
    RIGHT = 62,
    MSG_TYPE_COUNTER = 63,
    MSG_END = 10,
}
